server:
  port: 7879
#问答接口
interlocutionUrl: http://192.168.1.7:8017/add

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.4:3306/real_time_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.1.7:3306/real_time_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ami
    password: ami

mybatis-plus:
  type-aliases-package: com.example.database.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  path: logs/database
  level:
    io.netty.handler.logging: debug

fan-yu:
  # 调用异常提示信息
  error-message: 对不起，指令执行出错，请重试
  # 大模型配置
  large-model:
    # 请求地址
    url: http://192.168.1.22:7879/imitate/large/model
    # 数据出处
    source:
      # 前缀
      prefix: "根据"
      # 后缀
      suffix: "得出："
    param:
      # 请求参数模板
      template-file-path: E:/monkey/sources/java/database/src/main/resources/LargeModelParam
      # 响应数据存放字段
      response-data-field: answer
      # 响应数据出处存放字段
      response-data-source-field: docs
  # 中控系统配置
  hardware-control:
    enabled: true
    host: 192.168.1.7
    port: 8080
    timeout: 15
    request-command-config-file: E:/monkey/sources/java/database/RequestCommandCache
    receive-command-config-file: E:/monkey/sources/java/database/ReceiveCommandCache
  # 泰豪配置
  tell-how:
    # 图片地址
    pic-addr: http://graphic.xa.he.dc.sgcc.com.cn/osp/Graph/Navigator.html?graph=
    # 图片文件
    pic-config-file: E:/monkey/sources/java/database/PicDataCache
    # 服务地址
    service-addr: http://192.168.1.22:7879/imitate/tell-how