server:
  port: 7879
#问答接口
interlocutionUrl: http://192.168.1.7:8017/add
# 大模型接口
lager-model-url: http://10.122.66.165:10025

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.4:3306/real_time_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/real_time_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ami
    password: ami

mybatis-plus:
  type-aliases-package: com.example.database.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  path: logs/database
  level:
    io.netty.handler.logging: debug

fan-yu:
  # 调用异常提示信息
  error-message: 对不起，指令执行出错，请重试
  # 中控系统配置
  hardware-control:
    enabled: true
    host: 127.0.0.1
    port: 8080
    timeout: 15
    request-command-config-file: E:/monkey/product/config/RequestCommandCache
    receive-command-config-file: E:/monkey/product/config/ReceiveCommandCache