server:
  port: 7879
#问答接口
interlocutionUrl: http://SimCSE:8017/add

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/real_time_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ami
    password: Phenom2023

mybatis-plus:
  type-aliases-package: com.example.database.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path: /home/logs/database
  level:
    io.netty.handler.logging: debug

fan-yu:
  # 调用异常提示信息
  error-message: 对不起，指令执行出错，请重试
  # 大模型配置
  large-model:
    # 请求地址
    url: http://10.122.66.165:10025/diaodu
    # 数据出处
    source:
      # 前缀
      prefix: "根据"
      # 后缀
      suffix: "得出："
    param:
      # 请求参数模板
      template-file-path: /home/config/LargeModelParam
      # 响应数据存放字段
      response-data-field: answer
      # 响应数据出处存放字段
      response-data-source-field: docs1
  # 中控系统配置
  hardware-control:
    enabled: true
    host: 24.37.123.161
    port: 9876
    timeout: 15
    request-command-config-file: /home/config/RequestCommandCache
    receive-command-config-file: /home/config/ReceiveCommandCache
  # 南瑞相关配置
  nan-rui:
    # 服务地址
    service-addr: http://24.37.123.154:10000/nr
  # 泰豪配置
  tell-how:
    # 图片地址
    pic-addr: http://graphic.xa.he.dc.sgcc.com.cn/osp/Graph/Navigator.html?graph=
    # 图片文件
    pic-config-file: /home/config/PicDataCache
    # 服务地址
    service-addr: http://newoms.he.dc.sgcc.com.cn/cruise
    # 厂站配置文件
    substation-config-file: /home/config/SubstationDataCache
    # 溯源配置文件
    source-config-file: /home/config/SourceDataCache
    # 联络图访问地址
    contact-pic-addr: http://graphic.xa.he.dc.sgcc.com.cn/osp/Graph/Navigator.html?graph=dfe_test_cl.sys.pic.g;rtkeyId=
    # 溯源图访问地址
    source-pic-addr: http://graphic.xa.he.dc.sgcc.com.cn/osp/Graph/Navigator.html?graph=device_supply_path.sys.pic.g;rtkeyId=