server:
  port: 7879
#问答接口
interlocutionUrl: http://SimCSE:8017/add
# 大模型接口
lager-model-url: http://10.122.66.165:10025

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/real_time_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ami
    password: Phenom2023

mybatis-plus:
  type-aliases-package: com.example.database.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  path: logs/database
  level:
    io.netty.handler.logging: debug

fan-yu:
  # 中控配置
  hardware-control:
    enabled: false
    host: 127.0.0.1
    port: 8080
    timeout: 15
    request-command-config-file: D:/sources/robot-server/RequestCommandCache
    receive-command-config-file: D:/sources/robot-server/ReceiveCommandCache